# -*- coding: utf-8 -*-
"""Copy of Day 4 IOAI - MNIST II - Student.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t0d6C1ECt36MKFYjutK_ZDSLT6wr7PjX

# Day 4: Training a model with PyTorch - Handwriting Detection Part II

Welcome to day 4 of IOAI Canada training!

Today, we will build upon our handwriting detection neural network that we worked on yesterday. We will use a variety of methods to improve its accuracy.

If you have any questions, do not hesitate to ask questions in the zoom call.
"""



"""## Step 0: Imports

Run the code below to import the required packages.
"""

import numpy as np
import torch
import torchvision
import matplotlib.pyplot as plt
from torchvision import datasets, models, transforms
from torch import nn, optim
from PIL import Image

"""## Step 1: Data Augmentation

Data augmentation allows us to diversify our dataset, leading to improved training results. This is done by specifying a set of transforms (rotating, translating, and scaling the image, for example) that modify the image. The augmentation is then applied to the dataset.  

In addition, we will specify the device here instead of later in the code. This is generally good practice.
"""

# Image transform to perform data augmentation
transform = transforms.Compose([
    transforms.RandomAffine(degrees=(0, 20), translate=(0, 0.2), scale=(0.7, 1)), # Randomly rotate, translate and scale the image
    transforms.Grayscale(num_output_channels=3), # 3 channels instead of 1 since resnet only supports
    transforms.ToTensor(), # Convert image to a tensor
    transforms.Normalize(mean=(0.5,0.5,0.5), std=(0.5,0.5,0.5)) # Normalize the data, so that the gradients are more consistent, thus making it easier to train
])

# For our test set, we do not want to randomly rotate/translate/scale
transformtest = transforms.Compose([
    transforms.Grayscale(num_output_channels=3),
    transforms.ToTensor(),
    transforms.Normalize(mean=(0.5,0.5,0.5), std=(0.5,0.5,0.5))
])

batch_size = 100
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

# Load the MNIST datasets
train_dataset = datasets.MNIST(
    root='train',
    train=True,
    transform=transform,
    download=True
)

test_dataset = datasets.MNIST(
    root='test',
    train=False,
    transform=transformtest,
    download=True,
)

train_loader = torch.utils.data.DataLoader(
    dataset=train_dataset,
    batch_size=batch_size,
    shuffle=True
)

test_loader = torch.utils.data.DataLoader(
    dataset=test_dataset,
    batch_size=batch_size,
    shuffle=True
)

"""## Step 2: Display an image

To ensure that our dataset and transformation works, we will use the matplotlib library to display one of the images in the dataset.

However this time, we will load from the dataloader instead of the dataset. This ensures that the transformation is applied.
"""

# Display image from loader
# TO-DO: Fill in the blanks

img, lbl = next(iter(train_loader))
plt.imshow(img[0][0], cmap='gray') # Plot the first image in the batch (first [0]), then its first channel (second [0])
plt.title(f"{lbl[0]}") # Get the label of the first image in the batch ([0])
plt.show()

"""## Step 3: Defining the model, loss function, and optimizer

Here, we will use the ResNet18 network, which is a covolusional neural network, a type of model that will help increase performance in image recognition models.

We will use a different optimizer with higher performance than our previous one.
"""

# TO-DO: Define a ResNet18 model and Adam optimizer

model = models.resnet18(num_classes=10).to(device)
loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr = 0.005)

"""## Step 4: Training the model

Training the model is exactly like what we did yesterday, with some slight modifications to preprocessing the image.
"""

# Model Training

num_epochs = 10

for epoch in range(num_epochs):
  model.train()

  for i, data in enumerate(train_loader):
    # TO-DO: Write the code inside the training loop. Hint: You can copy most of the code from yesterday, but get rid of one line.
    images, labels = data
    images = images.to(device)
    labels = labels.to(device)

    pred = model(images)
    loss = loss_fn(pred, labels)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    if i % 100 == 99:
      print(f"Epoch {epoch+1}, Step {i+1}, Loss = {loss.item()}")

"""## Step 5: Evaluate the model

And so is evaluation. That's the beauty of machine learning - it's straightforward to adapt to other applications.
"""

# Model Evaluation

model.eval()
with torch.no_grad():

    i = 0
    total_accuracy = 0
    for images, labels in test_loader:
        # TO-DO: Write the code inside the evaluation loop. Hint: You can copy most of the code from yesterday, but get rid of one line.
        images, labels = data
        images = images.to(device)
        labels = labels.to(device)
        test_output = model(images)
        pred_y = torch.max(test_output, 1)[1].data.squeeze() # Get the class which has the highest probability (what number the model thinks the image corresponds to)
        batch_accuracy = (pred_y == labels).sum().item() / float(labels.size(0)) # Determines the accuracy of the model for this batch
        total_accuracy += batch_accuracy # Adds to the concurent accuracy
        i += 1

    accuracy = total_accuracy / i

print(f'Test Accuracy of the model on the 10000 test images: {accuracy:.3f}')

"""## Step 6: Our own handwriting data

Again, this is very similar to yesterday, without the extra preprocessing.
"""

# Import custom image
# TO-DO: Fill in the blanks

image_path = '/content/pixilart-drawing.png'
image = Image.open(image_path)

model.eval()

preprocess = transforms.Compose([
    transforms.Grayscale(num_output_channels=3),
    transforms.ToTensor(),
    transforms.Normalize(mean=(0.5,0.5,0.5), std=(0.5,0.5,0.5)),
])

image_tensor = preprocess(image).unsqueeze(dim=0)

with torch.no_grad():
    output = model(image_tensor.to(device))
    predicted = output.max(dim=1)[1].item()
    print(f"Predicted Class: {predicted}")